### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by optikfluffel** [bengourley/launch#1]
Hi :)
I tried jake together with launch a little but when I want to deploy I get this during the process:

```
$ ssh mydomain.com sudo stop site.WebApp-production && sudo start site.WebApp-production
sudo: no tty present and no askpass program specified

✘  Failed to restart site

jake aborted.
Error
  at fail (/usr/local/lib/node_modules/jake/lib/api.js:235:13)
  at /Users/udo/Projects/WebApp/Jakefile.coffee:31:16
  at ChildProcess.exports.remote (/Users/udo/Projects/WebApp/node_modules/launch/lib/action.js:39:5)
  at ChildProcess.EventEmitter.emit (events.js:91:17)
  at Process._handle.onexit (child_process.js:674:10)
```

Do you know how to get rid of this? I'm using Debian 6 on my remote machine.

Thanks

**Comment by bengourley** [comment]
Looks like your ssh user doesn't have sudo rights, and since it's being run without a terminal it can't ask for your password. Either give your ssh user sudo privileges or make upstart executable without sudo. (I would do the former).

**Comment by optikfluffel** [comment]
wow! that what I call fast support :D
i think the user has sudo rights but I always have to type a password if I do `sudo command`
wouldn't it be kind of insecure to don't ask for that?

**Comment by bengourley** [comment]
It is less secure because it means scripts (like this one) can elevate themselves to sudo rights, whereas currently it needs to be a user that knows your password. It's your call!
