### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by brucou** [bengourley/launch#2]
Hi Ben @bengourley 

I am wondering if you are still in need of the package name `launch`? If not, I would like to use that name for a CLI that I am developing. Let me know what you think. I see that there is still some traffic to it, but it seems low so I am thinking that maybe you are no longer using it. Let me know! Absolutely no problems if you'd rather keep it. Thanks

**Comment by bengourley** [comment]
Happy to do that. I can't remember how you go about that process with npm but let me know what you need me to do and I'll oblige. What's your cli for?

**Comment by brucou** [comment]
Thanks Ben,

I am also unsure how you relinquish package names. Let me check quickly. Here:

- instructions here: https://www.npmjs.com/policies/unpublish

It is actually possible that you won't be able to unpublish as I see
that you package has one dependent. That means there is one guy in the
world that is using this package (with <1 download a week) and as such
it is likely not possible to pull the carpet from below him.

Let me see if there are more options. Sorry to bother you with that.
My CLI is linked to my state machine library
(https://brucou.github.io/documentation/) and I want to gather all the
related commands in one CLI (compiling, conversion, etc.) with sub
commands. So sth like launch compile or launch convert etc. with like
6 different commands gathered under the launch umbrella.

There is nothing to do on your side for now. Will be back in touch soon.


On 5/26/20, Ben Gourley <notifications@github.com> wrote:
> Happy to do that. I can't remember how you go about that process with npm
> but let me know what you need me to do and I'll oblige. What's your cli
> for?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bengourley/launch/issues/2#issuecomment-633897041


-- 
---

**Comment by brucou** [comment]
You have one very strange dependent that will be blocking the unpublishing I am afraid: https://www.npmjs.com/package/hexlet_iwebinet

Closing this then.

**Comment by brucou** [comment]
Ah, I also reported that package to npm. If they do remove it, then I may come back and ask you again. In the meantime, there is nothing for you to do :-)
